"""MDT cleaning — written for the retired operator export.

.. note::
   **No notebook calls this any more.** MDT is now synthetic, generated by SUMO
   through Sionna-RT, and arrives in range by
   construction. The rules below are still worth keeping as assertions on
   generated data, but the cleaning *stage* no longer exists in the pipeline.
   Tracked in CLAUDE.md under *Known gaps*.

Every rule here is a *hard* rule: a record either violates a bound declared in
``configs/data.yaml`` or it does not. Nothing in this module looks at the
distribution of the data to decide what to drop.

Why that line matters
---------------------
A statistical filter fitted on the full dataset — an IQR fence, a z-score cut, a
quantile clip — sees the test records while deciding what counts as valid. The
resulting model is then evaluated on data that was shaped by knowledge of
itself, and the estimate comes out optimistic for a reason that is very hard to
find later. Statistical outlier handling belongs downstream, fitted on the
training split only.

Also runs as a script
---------------------
``python -m src.data.clean`` (or ``task clean:data``) performs cleaning and the
split without opening a notebook, so the DVC stage and the notebook cannot
diverge. Both call the same functions below.
"""

import hydra
import pandas as pd
from omegaconf import DictConfig


def drop_duplicates(df: pd.DataFrame, cfg: DictConfig) -> pd.DataFrame:
    """Remove exactly duplicated MDT records.

    Args:
        df: Raw MDT frame.
        cfg: Composed config; uses ``cfg.data.clean.drop_duplicates``.

    Returns:
        The frame with duplicate rows removed.

    Raises:
        NotImplementedError: Always — implement this module first.

    Notes:
        Deduplicate on the full record, not on ``ue_id`` alone. One UE
        legitimately contributes many measurements — that is what an MDT export
        is — so deduplicating by identifier would delete most of the dataset.

    Example:
        >>> df = drop_duplicates(mdt, cfg)
    """
    # TODO(1): return early when cfg.data.clean.drop_duplicates is false
    # TODO(2): drop_duplicates across all columns, not a subset
    raise NotImplementedError("src.data.clean.drop_duplicates")


def drop_invalid_rsrp(df: pd.DataFrame, cfg: DictConfig) -> pd.DataFrame:
    """Remove records whose RSRP is outside the reportable range.

    Args:
        df: MDT frame.
        cfg: Composed config; uses ``cfg.data.schema.mdt.columns.rsrp`` bounds
            and ``cfg.data.clean.drop_rsrp_out_of_range``.

    Returns:
        The frame with unreportable RSRP values removed.

    Raises:
        NotImplementedError: Always — implement this module first.

    Notes:
        The bounds come from 3GPP TS 38.133, not from the observed values. The
        raw export contains ``rsrp = 0.0``, which is not a measurable RSRP and
        is best read as a sentinel for "no report" — dropping it is a contract
        decision, not an outlier judgement.

        Count what this removes and surface it. A sentinel that suddenly appears
        in 40% of records is an upstream export bug, and a silent filter hides
        it.

    Example:
        >>> df = drop_invalid_rsrp(df, cfg)
    """
    # TODO(1): read min/max from cfg.data.schema.mdt.columns.rsrp
    # TODO(2): mask records outside [min, max], plus nulls
    # TODO(3): return the surviving records
    raise NotImplementedError("src.data.clean.drop_invalid_rsrp")


def drop_unknown_cells(df: pd.DataFrame, cells: pd.DataFrame, cfg: DictConfig) -> pd.DataFrame:
    """Remove MDT records measured against a cell absent from the configuration.

    Args:
        df: MDT frame.
        cells: Cell configuration from :func:`src.data.load.load_cell_config`.
        cfg: Composed config; uses ``cfg.data.clean.drop_unknown_cells``.

    Returns:
        The frame restricted to configured cells.

    Raises:
        NotImplementedError: Always — implement this module first.

    Notes:
        A measurement against a cell that has no position, azimuth or tilt
        cannot be placed in the Sionna-RT scene, so it can never be compared
        against a simulated radio map.

    Example:
        >>> df = drop_unknown_cells(df, cells, cfg)
    """
    # TODO(1): anti-join df.gcell_id against cells.gcell_id
    # TODO(2): report the distinct unknown ids, not just the row count
    raise NotImplementedError("src.data.clean.drop_unknown_cells")


def drop_outside_scene(df: pd.DataFrame, cfg: DictConfig) -> pd.DataFrame:
    """Remove records positioned outside the simulation scene.

    Args:
        df: MDT frame.
        cfg: Composed config; uses ``cfg.radio.grid.bounds`` when set, otherwise
            the bounding box of ``cfg.data.scene_file``.

    Returns:
        The frame restricted to the scene extent.

    Raises:
        NotImplementedError: Always — implement this module first.

    Notes:
        The evaluation grid only covers the scene, so a record outside it has no
        grid cell to contribute to. The raw export reaches roughly +/-4100 m in
        both axes while the cells sit within a far smaller area, so this is not
        a rare edge case.

        Take the bounds from the same source the radio map will use. Deriving
        them separately here is how the UE density grid and the RSRP grid end up
        misaligned by one cell, which is invisible until a KPI looks wrong.

    Example:
        >>> df = drop_outside_scene(df, cfg)
    """
    # TODO(1): resolve bounds via src.radio.scene.scene_bounds when cfg.radio.grid.bounds is null
    # TODO(2): mask records outside [xmin, xmax] x [ymin, ymax]
    raise NotImplementedError("src.data.clean.drop_outside_scene")


def clean(df: pd.DataFrame, cells: pd.DataFrame, cfg: DictConfig) -> pd.DataFrame:
    """Run the full cleaning sequence in order.

    Args:
        df: Raw MDT frame.
        cells: Cell configuration.
        cfg: Composed config; uses ``cfg.data.clean``.

    Returns:
        The cleaned MDT frame, ready for splitting.

    Raises:
        NotImplementedError: Always — implement this module first.

    Notes:
        Order matters for the audit, not for the result: applying the cheap
        structural filters before the spatial one keeps the "records removed by
        rule" table readable. Record the count before and after each step —
        A cleaning audit is that table, and it is the only evidence
        that the filters did what was intended.

    Example:
        >>> clean_df = clean(mdt, cells, cfg)
    """
    # TODO(1): apply drop_duplicates, drop_invalid_rsrp, drop_unknown_cells, drop_outside_scene
    # TODO(2): accumulate (rule, rows_before, rows_after) for the audit table
    # TODO(3): re-validate with schema.validate(..., strict=True) before returning
    raise NotImplementedError("src.data.clean.clean")


@hydra.main(version_base=None, config_path="../../configs", config_name="config")
def main(cfg: DictConfig) -> None:
    """Clean and split as a script. Legacy: see the module note.

    Args:
        cfg: Composed by Hydra from ``configs/``.

    Raises:
        NotImplementedError: Always — implement this module first.

    Example:
        >>> # task clean:data
    """
    # TODO(1): load_mdt + load_cell_config
    # TODO(2): clean(...)
    # TODO(3): split.train_test_split(...) and assert_no_leakage(...)
    # TODO(4): save_processed to cfg.data.train_path and cfg.data.test_path
    raise NotImplementedError("src.data.clean.main")


if __name__ == "__main__":
    main()
